### ISSUE TITLE
How to using your package?

### ISSUE THREAD

**Issue by stojankukrika** [mikicaivosevic/skrill-quick#1]
Hi,
Can you tell me more about how to using your package?
I begin with manual what i find in readme but can you tell me how and where to continue? I use it in Laravel project, create $skrill_request object with price, mail.. and $skrill_client, as you write in readme. And I ask, what to do next? 
Can you help me, bro?

**Comment by mikicaivosevic** [comment]
You need to redirect user on $client->getRedirectUrl(); When user pay, skrill will send you POST notificaiton. Read more about status_url on page 21

Please read this [pdf](https://www.skrill.com/fileadmin/content/pdf/Skrill_Quick_Checkout_Guide.pdf), page 9

**Comment by stojankukrika** [comment]
👍
